region: "us-west-2"
aws-iam-role: "arn:aws:iam::590178426343:role/SIONLambdaRole"
aws-vpc-subnets: "subnet-0719017fb24af22ac,subnet-076f5a2c0e07e6b1e"
aws-security-groups: "sg-0e3cfe7dde2d319b2"
s3-bucket-cos: "sion-backup%s"
s3-bucket-data: "sion-datapool"